### ISSUE TITLE
How to integrate this into a docker-compose.yml

### ISSUE THREAD

**Issue by fullstopslash** [djaydev/docker-nextcloud-news-updater#1]
My apologies if this is a super basic question, but I'm rather new to docker How would I integrate this into a docker-compose.yml file to install this in a nextcloud instance?

**Comment by djaydev** [comment]
Hi.  I've never ever used docker-compose so I can not help with that, but here's some info from the web https://docs.docker.com/compose/ .  From what I understand docker compose is a separate addon to docker and not required.

Once you get this docker container up and running, it will log into your nextcloud server and update the rss news reader addon.

To run this docker without docker-compose run the following command, replacing sample values with your own.

```
docker run -d \
--name=nextcloud-news-updater \
-e NEXTCLOUD_URL=mynextcloud.homeserver.com \
-e NEXTCLOUD_USER=my-nextcloud-user \
-e NEXTCLOUD_TOKEN=my-nextcloud-user-password \
djaydev/nextcloud-news-updater
```
